using CryptoExchange.Net.SharedApis;

namespace Kucoin.Net.Interfaces.Clients.UnifiedApi
{
    /// <summary>
    /// Shared API interface. Shared APIs provide a common,
    /// exchange-independent contract for accessing functionality across different
    /// exchange client libraries.
    /// </summary>
    public interface IKucoinRestClientUnifiedSharedApi :
        IGetTickerRest,
        IGetAllTickersRest,
        IGetAssetRest,
        IGetAllAssetsRest,
        IGetBalancesRest,
        IGetDepositAddressesRest,
        IGetDepositHistoryRest,
        IGetFeesRest,
        IGetFundingInfoRest,
        IGetFundingRateHistoryRest,
        IGetUserFundingHistoryRest,
        IGetIndexPriceRest,
        IGetAllIndexPricesRest,
        IGetMarkPriceRest,
        IGetAllMarkPricesRest,
        IGetIndexPriceKlinesRest,
        IGetMarkPriceKlinesRest,
        IGetKlinesRest,
        IGetLedgerRest,
        IGetLeverageRest,
        ISetLeverageRest,
        IGetLeverageTiersRest,
        IGetOpenInterestRest,
        IGetBookTickerRest,
        IGetOrderBookRest,
        IGetSpotSymbolsRest,
        IGetFuturesSymbolsRest,
        IGetRecentTradesRest,
        ITransferRest,
        IGetWithdrawalHistoryRest,
        IPlaceSpotOrderRest,
        IGetSpotOrderRest,
        IGetSpotOrderByClientOrderId,
        IGetOpenSpotOrdersRest,
        IGetClosedSpotOrdersRest,
        IGetSpotOrderTradesRest,
        IGetSpotUserTradeHistoryRest,
        ICancelSpotOrderRest,
        ICancelSpotOrderByClientOrderIdRest,
        ICancelAllSpotSymbolOrdersRest,
        IEditSpotOrderRest,
        IEditSpotOrderByClientOrderIdRest,
        IPlaceFuturesOrderRest,
        IGetFuturesOrderRest,
        IGetFuturesOrderByClientOrderId,
        IGetOpenFuturesOrdersRest,
        IGetClosedFuturesOrdersRest,
        IGetFuturesOrderTradesRest,
        IGetFuturesUserTradeHistoryRest,
        ICancelFuturesOrderRest,
        ICancelFuturesOrderByClientOrderIdRest,
        ICancelAllFuturesSymbolOrdersRest,
        IEditFuturesOrderRest,
        IEditFuturesOrderByClientOrderIdRest,
        IGetPositionsRest,
        IGetPositionHistoryRest,
        IPlaceSpotTriggerOrderRest,
        IGetSpotTriggerOrderRest,
        ICancelSpotTriggerOrderRest,
        IPlaceFuturesTriggerOrderRest,
        IGetFuturesTriggerOrderRest,
        ICancelFuturesTriggerOrderRest
    {
    }
}
